# Generated by Django 3.2 on 2021-04-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='docfile',
            field=models.FileField(blank=True, default='', upload_to='documents/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='imgDoc',
            field=models.ImageField(blank=True, default='', upload_to='images/'),
        ),
    ]
