# Generated by Django 3.2 on 2021-04-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0004_remove_userprofile_imgdoc'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='imagefile',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='imgDoc',
            field=models.ImageField(blank=True, default='', upload_to='images/'),
        ),
    ]
